### ISSUE TITLE
JSON crash when trying to get ShowConnectedDevicesAsync

### ISSUE THREAD

**Issue by mmpab** [StanlyRod/lifx-library#1]
Trying to get the list of connected devices.
`
LightSearcher.SetTokenKey(tokenKey);
var devices = await LightSearcher.ShowConnectedDevicesAsync()
`
when I get this JSON error:

System.Text.Json.JsonException: 'The JSON value could not be converted to System.Int32. Path: $[2].color.hue | LineNumber: 91 | BytePositionInLine: 18.'
Inner exception:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.

I have a few A19 bulbs, but then I also have three original LIFX bulbs from the very first Kickstarter. Not sure, but could they be the cause? But I can control them when going directly to them.
(Model: LIFX Original, Firmware: v2.1)

**Comment by StanlyRod** [comment]
Apparently it's working fine with the model that I have I am using the MODEL: LIFX Color A19 1100lm, FIRMWARE VERSION : v3.70

Did you try to cut off the power on the original Lifx bulbs and test the code just on the A19 models ? try that and let me know how it goes. Another thing that you can do is try to do an http get request just on the original models with the official LIFX API website [https://api.developer.lifx.com/reference/list-lights](url) and send me the JSON response to see what I can do with that because I think the error come from the original models.

![lfi](https://github.com/StanlyRod/lifx-library/assets/76764572/131c0c4c-cced-4e75-9744-88589bd46d56)
![bulb](https://github.com/StanlyRod/lifx-library/assets/76764572/1bb63173-11d6-4850-b50d-d7156818f120)

**Comment by spindisc** [comment]
Sorry for the delayd answer. I unplugged my original (the oldest) and tried again. But still the same error. There are now ony 3 LIFX devices and all of them have the same spec:
_Model: LIFX (A19)
Firmware: v2.90 (Up to date)_

I can still reached and control them individually but using the ShowConnectedDevicesAsync will make it crash.
---


The JSON value could not be converted to System.Int32. Path: $[6].color.hue | LineNumber: 258 | BytePositionInLine: 18.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at LifxLibrary.LightSearcher.<ShowConnectedDevicesAsync>d__5.MoveNext()
   at LIFXRPG.frmLifxRpg.<btnDetect_Click>d__6.MoveNext() in C:\Dropbox\repos\LIFXRPG\LIFXRPG\Form1.cs:line 38

**Comment by spindisc** [comment]
Ok, debugged your code. The api call to LIFX returns all my devices, including all my old ones. They are just flagged as "connected: false" in the json. But they are not causing the trouble.

But one of my devices has a double value for hue, not an int. So I guess both hue and saturation can be a doubles. Probably not kelvin. Changing from int to double in your code fixed it. I did not make a pullrequest since I only verified that, not the rest of your repo. But change this and I guess it will work.

        "color": {
            "hue": 30.73,
            "saturation": 0,
            "kelvin": 3500
        },

**Comment by StanlyRod** [comment]
Thanks so much for the clarifications,. Now I can see very clear what is the issue, I will fix the problem and I will give you the credits for your contribution.
![lifxjson](https://github.com/StanlyRod/lifx-library/assets/76764572/8a24fb5c-5ae0-4a0b-a571-f86709c5b9c3)

**Comment by StanlyRod** [comment]
In this release, the JSON deserialization issue associated with the ShowConnectedDevicesAsync() method has been resolved.
Thanks to @mmpab @spindisc
